name: Flutter Desktop Build and Test

on:
  push:
    branches:
      - main
  # 一時的にブランチを増やす
      - dev
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  # Windows向けのビルドジョブ
  build-windows:
    name: Build and Test Windows App
    runs-on: windows-latest
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Flutterをセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      # 3. デスクトップサポートを有効化
      - name: Enable desktop support
        run: flutter config --enable-windows-desktop

      # 4. 環境を確認
      - name: Verify Flutter environment
        run: flutter doctor -v

      # 5. Flutterの依存関係をキャッシュ
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            build/
          key: ${{ runner.os }}-flutter-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # 6. Flutterの依存関係を取得
      - name: Install dependencies
        run: flutter pub get

      # 7. テストを実行
      - name: Run tests
        run: flutter test

      # 8. Windows向けにビルド
      - name: Build Windows App
        run: flutter build windows --release

      # 9. ビルド成果物を保存
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: build\windows\x64\runner\Release\

  # macOS向けのビルドジョブ
  build-macos:
    name: Build and Test macOS App
    runs-on: macos-latest
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Flutterをセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      # 3. デスクトップサポートを有効化
      - name: Enable desktop support
        run: flutter config --enable-macos-desktop

      # 4. 環境を確認
      - name: Verify Flutter environment
        run: flutter doctor -v

      # 5. Flutterの依存関係を取得
      - name: Install dependencies
        run: flutter pub get

      # 6. テストを実行
      - name: Run tests
        run: flutter test

      # 7. macOS向けにビルド
      - name: Build macOS App
        run: flutter build macos --release

      # 8. ビルド成果物を保存
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-build
          path: build/macos/Build/Products/Release/*.app

  # GitHub Releasesにビルド成果物をアップロード（タグプッシュ時のみ）
  release:
    name: Create Release
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Windows ビルド成果物をダウンロード
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: windows-build
          path: ./artifacts/windows

      # 3. macOS ビルド成果物をダウンロード
      - name: Download macOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: macos-build
          path: ./artifacts/macos

      # 4. Windows用ZIPファイルを作成
      - name: Create Windows ZIP
        run: |
          cd ./artifacts/windows
          zip -r ../../vital-data-viewer-windows-${{ github.ref_name }}.zip .

      # 5. macOS用ZIPファイルを作成
      - name: Create macOS ZIP
        run: |
          cd ./artifacts/macos
          zip -r ../../vital-data-viewer-macos-${{ github.ref_name }}.zip .

      # 6. GitHub Releaseを作成してファイルをアップロード
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            vital-data-viewer-windows-${{ github.ref_name }}.zip
            vital-data-viewer-macos-${{ github.ref_name }}.zip
          generate_release_notes: true