name: Flutter Desktop Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Flutter Desktop Apps
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        platform: [windows, linux, macos]
    runs-on: ${{ matrix.os }}

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Flutterをセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.4'
          channel: 'stable'

      # 3. デスクトップサポートを有効化
      - name: Enable desktop support
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            flutter config --enable-windows-desktop
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            flutter config --enable-linux-desktop
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            flutter config --enable-macos-desktop
          fi

      # 4. 環境を確認
      - name: Verify Flutter environment
        run: flutter doctor -v

      # 5. Flutterの依存関係を取得
      - name: Install dependencies
        run: flutter pub get

      # 6. 各プラットフォーム向けにビルド
      - name: Build for ${{ matrix.platform }}
        run: |
          if [ "${{ matrix.platform }}" == "windows" ]; then
            flutter build windows --release
          elif [ "${{ matrix.platform }}" == "linux" ]; then
            flutter build linux --release
          elif [ "${{ matrix.platform }}" == "macos" ]; then
            flutter build macos --release
          fi

      # 7. ビルド成果物を保存
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-build
          path: |
            build/windows/runner/Release/*.exe
            build/linux/runner/release/*.AppImage
            build/macos/Build/Products/Release/*.app