name: Release Build and Deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  # Windows用リリースビルド
  release-windows:
    name: Release Windows Build
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Flutterをセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      # 3. デスクトップサポートを有効化
      - name: Enable desktop support
        run: flutter config --enable-windows-desktop

      # 4. Flutterの依存関係を取得
      - name: Install dependencies
        run: flutter pub get

      # 5. Windows向けにビルド
      - name: Build Windows App
        run: flutter build windows --release

      # 6. Windows用ZIPファイルを作成
      - name: Create Windows ZIP
        run: |
          cd build\windows\x64\runner\Release
          tar -czf ..\..\..\..\..\..\vital-data-viewer-windows-${{ github.ref_name }}.zip *
        shell: cmd

      # 7. GitHub Releaseを作成してファイルをアップロード
      - name: Upload Windows Release
        uses: softprops/action-gh-release@v2
        with:
          files: vital-data-viewer-windows-${{ github.ref_name }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: false

  # macOS用リリースビルド
  release-macos:
    name: Release macOS Build
    runs-on: macos-latest
    permissions:
      contents: write

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Flutterをセットアップ
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      # 3. デスクトップサポートを有効化
      - name: Enable desktop support
        run: flutter config --enable-macos-desktop

      # 4. Flutterの依存関係を取得
      - name: Install dependencies
        run: flutter pub get

      # 5. macOS向けにビルド
      - name: Build macOS App
        run: flutter build macos --release

      # 6. macOS用ZIPファイルを作成
      - name: Create macOS ZIP
        run: |
          cd build/macos/Build/Products/Release
          zip -r ../../../../../vital-data-viewer-macos-${{ github.ref_name }}.zip *.app

      # 7. GitHub Releaseを作成してファイルをアップロード
      - name: Upload macOS Release
        uses: softprops/action-gh-release@v2
        with:
          files: vital-data-viewer-macos-${{ github.ref_name }}.zip
          generate_release_notes: true
          fail_on_unmatched_files: false